version: '3'
services:
  frontend:
    build: ./front
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - todo-network

  backend:
    build: ./go-backend
    ports:
      - '8080:8080'
    networks:
      - todo-network

networks:
  todo-network:
